/* Copyright (C) 2016 Gan Quan <coin2028@hotmail.com>
 *
 * This file is part of AIMv6.
 *
 * AIMv6 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AIMv6 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <aim/device.h>
#include <arch-trap.h>
#include <cp0regdef.h>
#include <timer.h>
#include <errno.h>
#include <io.h>
#include <mp.h>
#include <platform.h>
#include <mach-conf.h>
#include <asm-generic/funcs.h>

#define PANIC_MASK	0x80000000

static int (*__io_interrupt_handler[NR_IRQS])(void);

/*
 * After some struggling I decided to couple HyperTransport, Loongson 3A
 * interrupt router, and Intel 8259 into the machine code...
 */

void init_IRQ(void)
{
	struct bus_device *mem;
	bus_read_fp mread8, mread32;
	bus_write_fp mwrite8, mwrite32;
	uint64_t inten;

	mem = (struct bus_device *)dev_from_name("memory");
	mread8 = mem->bus_driver.get_read_fp(mem, 8);
	mread32 = mem->bus_driver.get_read_fp(mem, 32);
	mwrite8 = mem->bus_driver.get_write_fp(mem, 8);
	mwrite32 = mem->bus_driver.get_write_fp(mem, 32);

	mread32(mem, LOONGSON3A_INTROUTER_BASE, LOONGSON3A_INTROUTER_INTEN,
	    &inten);
	/* Route LPC interrupt to Core 0 IP2 */
	mwrite8(mem, LOONGSON3A_INTROUTER_BASE, LOONGSON3A_INTROUTER_LPC,
	    LOONGSON3A_INTROUTER_IP(2) | LOONGSON3A_INTROUTER_CORE(0));
	inten |= 1 << LOONGSON3A_INTROUTER_LPC;
	/* Route all HT1 interrupts to Core 0 IP3 */
	for (int i = 0; i < 7; ++i) {
		mwrite8(mem, LOONGSON3A_INTROUTER_BASE,
		    LOONGSON3A_INTROUTER_HT1(i),
		    LOONGSON3A_INTROUTER_IP(3) | LOONGSON3A_INTROUTER_CORE(0));
		inten |= 1 << LOONGSON3A_INTROUTER_HT1(i);
	}
	/* Enable LPC interrupt and HT1 interrupts */
	mwrite32(mem, LOONGSON3A_INTROUTER_BASE, LOONGSON3A_INTROUTER_INTENSET,
	    inten);

	/* Enable HT1 interrupts with IRQ 0-31 */
	mwrite32(mem, LOONGSON3A_HT1_CFG_BASE, LOONGSON3A_HT_IEN0, 0xffffffff);

	/* Initialize Intel 8259 */
	extern void i8259_init(bool auto_eoi);
	i8259_init(false);

	/* IRQ 7 and IRQ 15 are Intel 8259 spurious interrupts */
	__io_interrupt_handler[7] = NOP;
	__io_interrupt_handler[15] = NOP;
}

static int __lpc_interrupt(struct trapframe *regs)
{
	/* Currently on Loongson 3A the only LPC interrupt is generated by UART */
	return __io_interrupt_handler[IRQ_UART]();
}

static int __ht_interrupt(struct trapframe *regs)
{
	struct bus_device *mem;
	bus_read_fp mread32;
	bus_write_fp mwrite32;
	uint64_t irqmask;
	extern void i8259_eoi(void);

	mem = (struct bus_device *)dev_from_name("memory");
	mread32 = mem->bus_driver.get_read_fp(mem, 32);
	mwrite32 = mem->bus_driver.get_write_fp(mem, 32);

	/* Acknowledge interrupt on HT side */
	mread32(mem, LOONGSON3A_HT1_CFG_BASE, LOONGSON3A_HT_ISR0, &irqmask);
	mwrite32(mem, LOONGSON3A_HT1_CFG_BASE, LOONGSON3A_HT_ISR0, irqmask);

	for (int i = 15; i >= 0; --i) {
		if (irqmask & (1 << i)) {
			__io_interrupt_handler[i]();
			/* Acknowledge highest interrupt on 8259 side */
			i8259_eoi();
		}
	}
	return 0;
}

static int __timer_interrupt(struct trapframe *regs)
{
	handle_timer_interrupt();
	return 0;
}

static int __ipi_interrupt(struct trapframe *regs)
{
	unsigned int ipi_status;

	ipi_status = read32(LOONGSON3A_COREx_IPI_STATUS(cpuid()));
	write32(LOONGSON3A_COREx_IPI_CLEAR(cpuid()), ipi_status);

	if (ipi_status & PANIC_MASK) {
		__local_panic();
		/* NOTREACHED */
		return -EINVAL;
	} else {
		/* TODO: convert IPI status to arch-independent message */
		return handle_ipi_interrupt(ipi_status);
	}
}

static int (*__dispatch[])(struct trapframe *) = {
	NULL,			/* Soft interrupt 0 */
	NULL,			/* Soft interrupt 1 */
	__lpc_interrupt,	/* LPC/UART interrupt */
	__ht_interrupt,		/* HT1 interrupt */
	NULL,			/* Unused */
	NULL,			/* Unused */
	__ipi_interrupt,	/* IPI */
	__timer_interrupt	/* Timer */
};

/* TODO: move to mach-specific code */
int handle_interrupt(struct trapframe *regs)
{
	int i;

	for (i = 7; i >= 0; --i) {
		if (regs->cause & regs->status & CR_IPx(i)) {
			if (__dispatch[i] != NULL)
				return __dispatch[i](regs);
			else
				return -ENOENT;
		}
	}
	/* NOTREACHED */
	return -EINVAL;
}

void add_interrupt_handler(int (*handler)(void), int irq)
{
	__io_interrupt_handler[irq] = handler;
}

void panic_other_cpus(void)
{
	int i;

	for (i = 0; i < nr_cpus(); ++i) {
		if (i == cpuid())
			continue;
		write32(LOONGSON3A_COREx_IPI_SET(i), PANIC_MASK);
	}
}

